name    'trlinkin-simulate'
version '0.0.1'
source 'https://github.com/trlinkin/puppet-simulate'
author 'Thomas Linkin'
license 'Apache License, Version 2.0'
summary 'Simulate type for Puppet development testing'
project_page 'https://github.com/trlinkin/puppet-enhanced-notify'
